# Generated by Django 4.1.3 on 2023-01-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='task_description',
            field=models.TextField(default='No description'),
        ),
    ]
