# Generated by Django 4.1.3 on 2023-01-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_todoitem_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='task_complete',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='task_description',
            field=models.TextField(),
        ),
    ]
