# Generated by Django 4.1.3 on 2023-01-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category1',
            new_name='category',
        ),
    ]
